/* llvm_gen_be.cpp - LLVM IR-generating back end core */
#include "basic_hdrs.h"
#include "fe_common.h"
#include "llvm_gen_be_internal.h"

#if BACK_END_IS_LLVM_GEN_BE
#include <llvm/Bitcode/BitcodeWriter.h>
#include <llvm/IR/Verifier.h>
#include <llvm/Support/FileSystem.h>
#include <llvm/Support/raw_ostream.h>

BEGIN_EDG_NAMESPACE

LLVMBackendState* be_state = nullptr;

std::string build_data_layout() {
  std::string dl = "";
  // Endianness
#if TARG_LITTLE_ENDIAN
  dl += "e-";
#else
  dl += "E-";
#endif

#if TARG_MAC_OS_X
  dl += "m:o-";
#elif TARG_MICROSOFT
  dl += "m:w-";
#else
  dl += "m:e-";
#endif

  // Pointer size
  dl += "p:" + std::to_string(TARG_SIZEOF_POINTER * TARG_CHAR_BIT) + ":" + std::to_string(TARG_SIZEOF_POINTER * TARG_CHAR_BIT) + "-";

  // Data layout construction based on EDG target macros
  dl += "i8:" LLVM_BE_STR(INTERNAL_TARG_CHAR_BIT) "-";
  dl += "i16:" + std::to_string(TARG_SIZEOF_SHORT * TARG_CHAR_BIT) + "-";
  dl += "i32:" + std::to_string(TARG_SIZEOF_INT * TARG_CHAR_BIT) + "-";
  dl += "i64:" + std::to_string(TARG_SIZEOF_LONG_LONG * TARG_CHAR_BIT) + "-";
  dl += "f32:" + std::to_string(TARG_SIZEOF_FLOAT * TARG_CHAR_BIT) + "-";
  dl += "f64:" + std::to_string(TARG_SIZEOF_DOUBLE * TARG_CHAR_BIT) + "-";
  dl += "f128:" + std::to_string(TARG_SIZEOF_LONG_DOUBLE * TARG_CHAR_BIT);

  return dl;
}

void generate_llvm_output_file(const char* base_name) {
  std::string file_name;
  bool emit_bc = false; // Add CLI toggle logic later if needed

  if (gen_llvm_file_name) {
    file_name = gen_llvm_file_name;
  } else if (base_name) {
    const char* derived = derived_name(base_name, emit_bc ? ".bc" : ".ll");
    if (derived) file_name = derived;
  }

  if (file_name.empty()) {
    file_name = emit_bc ? "output.bc" : "output.ll";
  }

  std::string err_str;
  llvm::raw_string_ostream os(err_str);
  if (llvm::verifyModule(*be_state->module, &os)) {
    // If it fails, report via EDG error handling
    f_error(ec_generated_c, err_str.c_str());
  }

  std::error_code EC;
  llvm::raw_fd_ostream dest(file_name, EC, llvm::sys::fs::OF_None);

  if (EC) {
    f_error(ec_file_open_failed, file_name.c_str());
    return;
  }

  if (emit_bc) {
    llvm::WriteBitcodeToFile(*be_state->module, dest);
  } else {
    be_state->module->print(dest, nullptr);
  }
}

static void emit_global_ctors_and_dtors() {
  std::vector<llvm::Constant*> ctors;
  std::vector<llvm::Constant*> dtors;
  llvm::Type* int32_ty = llvm::Type::getInt32Ty(*be_state->context);
  llvm::Type* void_fn_ty = llvm::FunctionType::get(llvm::Type::getVoidTy(*be_state->context), false);
  llvm::Type* ptr_ty = void_fn_ty->getPointerTo();
  llvm::StructType* ctor_struct_ty = llvm::StructType::get(
      int32_ty, ptr_ty, ptr_ty); // { i32, void ()*, i8* }

  if (il_header.primary_scope) {
    for (a_routine_ptr routine = il_header.primary_scope->routines; routine != nullptr; routine = routine->next) {
      if (!routine->source_corresp.name) continue;
      
      bool is_ctor = routine->is_initialization_routine;
      bool is_dtor = routine->is_finalization_routine;
      int ctor_priority_val = 65535;
      int dtor_priority_val = 65535;

#if GNU_EXTENSIONS_ALLOWED || REDEFINE_EXTNAME_PRAGMA_ENABLED
#if GNU_INIT_PRIORITY_ATTRIBUTE_ALLOWED
      if (routine->has_ctor_priority) {
        is_ctor = true;
        ctor_priority_val = gnu_routine_supp(routine)->ctor_priority;
      }
      if (routine->has_dtor_priority) {
        is_dtor = true;
        dtor_priority_val = gnu_routine_supp(routine)->dtor_priority;
      }
#if DO_IL_LOWERING
      if (routine->is_initialization_routine && gnu_routine_supp_or_null(routine) && gnu_routine_supp(routine)->init_priority != 0) {
         ctor_priority_val = gnu_routine_supp(routine)->init_priority;
      }
      // Assuming finalization routines might also have init_priority if generated by lowering
      if (routine->is_finalization_routine && gnu_routine_supp_or_null(routine) && gnu_routine_supp(routine)->init_priority != 0) {
         dtor_priority_val = gnu_routine_supp(routine)->init_priority;
      }
#endif // DO_IL_LOWERING
#endif // GNU_INIT_PRIORITY_ATTRIBUTE_ALLOWED
#endif // GNU_EXTENSIONS_ALLOWED || REDEFINE_EXTNAME_PRAGMA_ENABLED

      if (is_ctor || is_dtor) {
        llvm::Function* func = be_state->module->getFunction(routine->source_corresp.name);
        if (func) {
          llvm::Constant* fn_ptr = llvm::ConstantExpr::getBitCast(func, ptr_ty);
          llvm::Constant* null_ptr = llvm::ConstantPointerNull::get(llvm::cast<llvm::PointerType>(ptr_ty));
          
          if (is_ctor) {
            llvm::Constant* priority = llvm::ConstantInt::get(int32_ty, ctor_priority_val);
            ctors.push_back(llvm::ConstantStruct::get(ctor_struct_ty, {priority, fn_ptr, null_ptr}));
          }
          if (is_dtor) {
            llvm::Constant* priority = llvm::ConstantInt::get(int32_ty, dtor_priority_val);
            dtors.push_back(llvm::ConstantStruct::get(ctor_struct_ty, {priority, fn_ptr, null_ptr}));
          }
        }
      }
    }
  }

  if (!ctors.empty()) {
    llvm::ArrayType* ctors_array_ty = llvm::ArrayType::get(ctor_struct_ty, ctors.size());
    llvm::Constant* ctors_array = llvm::ConstantArray::get(ctors_array_ty, ctors);
    new llvm::GlobalVariable(
        *be_state->module, ctors_array_ty, false,
        llvm::GlobalValue::AppendingLinkage, ctors_array, "llvm.global_ctors");
  }
  
  if (!dtors.empty()) {
    llvm::ArrayType* dtors_array_ty = llvm::ArrayType::get(ctor_struct_ty, dtors.size());
    llvm::Constant* dtors_array = llvm::ConstantArray::get(dtors_array_ty, dtors);
    new llvm::GlobalVariable(
        *be_state->module, dtors_array_ty, false,
        llvm::GlobalValue::AppendingLinkage, dtors_array, "llvm.global_dtors");
  }
}

void llvm_gen_be(void)
{
  be_state = new LLVMBackendState();
  be_state->context = std::make_unique<llvm::LLVMContext>();
  be_state->module = std::make_unique<llvm::Module>("edg_module", *be_state->context);
  be_state->builder = std::make_unique<llvm::IRBuilder<>>(*be_state->context);
  be_state->module->setDataLayout(build_data_layout());

  emit_global_variables();
  emit_function_declarations();
  emit_function_definitions();
  emit_global_ctors_and_dtors();

  generate_llvm_output_file(primary_source_file_name);
}

#if !STANDALONE_UTILITY_PROGRAM

void back_end(void)
/*
Simple "back end" that generates LLVM IR. This version is for use as a
subroutine called in the same program as the front end.
*/
{
#if IL_SHOULD_BE_WRITTEN_TO_FILE
  /* If the intermediate language was written to a file, read it back in. */
  primary_source_file_name = NULL;
  if (skip_il_read) {
    /* The IL should still be in memory. */
  } else {
    il_read(f_il_output);
  }  /* if */
  primary_source_file_name = il_header.primary_source_file->file_name;
#endif /* IL_SHOULD_BE_WRITTEN_TO_FILE */

  /* Generate LLVM IR. */
  llvm_gen_be();
}

#endif /* !STANDALONE_UTILITY_PROGRAM */

#if MAKE_FRONT_END_CALLABLE

void llvm_gen_be_cleanup(void)
/*
This routine is called at the end of compilation, or if compilation is
terminated prematurely for some reason. It performs any cleanup operations
required.
*/
{
  if (be_state) {
    delete be_state;
    be_state = nullptr;
  }
}

#endif /* MAKE_FRONT_END_CALLABLE */

END_EDG_NAMESPACE
#endif /* BACK_END_IS_LLVM_GEN_BE */
